# Generated by Django 6.1 on 2026-08-27 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_date_alter_payment_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
