# Generated by Django 6.1 on 2026-09-01 10:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_coursesubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="coursesubscription",
            constraint=models.UniqueConstraint(
                fields=("course", "user"),
                name="unique_course_subscription",
                violation_error_message="User already has subscription for this course.",
            ),
        ),
    ]
