# Generated by Django 6.1 on 2026-09-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_coursesubscription_unique_course_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Payment status"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_checkout_session",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Stripe Checkout Session Id"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
