# Generated by Django 6.1 on 2026-09-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0006_payment_status_payment_stripe_checkout_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_checkout_url",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Stripe Checkout Session url"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="stripe_checkout_session",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Stripe Checkout Session Id"),
        ),
    ]
