# Generated by Django 6.1 on 2026-09-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_payment_stripe_checkout_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Стоимость"),
        ),
    ]
