# Generated by Django 6.1 on 2026-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0008_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(default=0, verbose_name="Стоимость"),
        ),
    ]
