# Generated by Django 6.1 on 2026-09-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0009_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Stripe Price ID"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Stripe Product ID"),
        ),
    ]
